@import org.svenehrke.demo.bdscomponentsdemo.demos.Main.Ctx


@param Ctx ctx

<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="/webjars/baloise-design-system/19.2.0/@baloise/ds-styles/css/all.min.css" />
	<script src="https://cdn.jsdelivr.net/npm/alpinejs@3.14.9/dist/cdn.min.js" defer></script>
	<link rel="stylesheet" href="/jte-heading-component.css" /> <%-- See note in css file--%>
</head>

<body>
	@template.jte.menu()
</body>
</html>
